# Generated by Django 4.2.2 on 2023-09-03 21:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attacker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_ip', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_to_exec', models.TextField(null=True)),
                ('command_to_exec_timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_results', models.TextField(null=True)),
                ('command_results_timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_ip', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('victim_name', models.CharField(max_length=100, null=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attacker')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.victim')),
            ],
        ),
    ]
