# Generated by Django 4.2.2 on 2023-09-03 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_to_exec_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='commandresult',
            name='command_results_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
